version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:80
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    command: npm run start:dev
    environment:
      MONGODB_URI: "mongodb://db:27017"

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db
